import os
from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas

def generate_pdf(deal: dict, out_path: str):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    c = canvas.Canvas(out_path, pagesize=LETTER)

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, 760, "VortexAI Deal Contract Draft")

    c.setFont("Helvetica", 12)
    y = 730
    for k in ["id", "title", "location", "asset_type", "source", "price", "market_value", "ai_score", "grade"]:
        c.drawString(50, y, f"{k}: {deal.get(k)}")
        y -= 18

    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 80, "Generated by VortexAI (draft) - verify before use.")
    c.save()
