import json
import time
import uuid
import requests
from pathlib import Path

API_URL = "https://vortexai-backend-production.up.railway.app/deals/create"
SOURCES_PATH = Path("data/sources_usa.json")

HEADERS = {
    "Content-Type": "application/json"
}

DELAY_SECONDS = 180  # 3 minutes → ~20/day

def load_sources():
    with open(SOURCES_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

def build_deal(source_name, asset_type, location):
    return {
        "source": source_name,
        "external_id": f"{source_name}-{uuid.uuid4()}",
        "asset_type": asset_type,
        "title": f"{location} Off-Market {asset_type.title()} Deal",
        "description": "Generated by VortexAI scraper worker",
        "location": location,
        "url": "https://example.com",
        "price": 150000 + int(uuid.uuid4().int % 200000),
        "currency": "USD"
    }

def send_deal(deal):
    r = requests.post(API_URL, json=deal, headers=HEADERS, timeout=15)
    if r.status_code == 200:
        print("✅ INGESTED:", deal["external_id"])
    else:
        print("❌ ERROR:", r.status_code, r.text)

def run():
    sources = load_sources()

    while True:
        for asset_type, items in sources.items():
            for src in items:
                deal = build_deal(
                    source_name=src["name"],
                    asset_type=asset_type,
                    location=src.get("city", "USA")
                )
                send_deal(deal)
                time.sleep(DELAY_SECONDS)

if __name__ == "__main__":
    print("🚀 VortexAI Production Scraper Started")
    run()
