import json
import time
import requests
import uuid
from pathlib import Path

API_URL = "http://localhost:8080/deals/create"  # change in prod
SOURCES_PATH = Path("data/sources_usa.json")

HEADERS = {
    "Content-Type": "application/json"
}

def load_sources():
    with open(SOURCES_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

def build_fake_deal(source_name, asset_type):
    return {
        "source": source_name,
        "external_id": str(uuid.uuid4()),
        "asset_type": asset_type,
        "title": f"Auto deal from {source_name}",
        "description": "Generated by scraper worker",
        "location": "USA",
        "url": "https://example.com",
        "price": 100000,
        "currency": "USD"
    }

def send_deal(deal):
    r = requests.post(API_URL, json=deal, headers=HEADERS, timeout=10)
    if r.status_code != 200:
        print("❌ Failed:", r.text)
    else:
        print("✅ Sent:", deal["title"])

def run():
    sources = load_sources()

    for category, items in sources.items():
        for src in items:
            deal = build_fake_deal(
                source_name=src["name"],
                asset_type=category
            )
            send_deal(deal)
            time.sleep(2)  # throttle

if __name__ == "__main__":
    print("🚀 Scraper worker started")
    run()
